stages:
- name: 构建发布镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./todo-consumer/Dockerfile
      buildContext: ./todo-consumer
      tag: yom535/example:v1
      pushRemote: true
      registry: registry.us-west-1.aliyuncs.com
timeout: 60
notification: {}
