stages:
- name: 打包
  steps:
  - runScriptConfig:
      image: golang:latest
      shellScript: |-
        ls -al
        mkdir -p $GOPATH/src/yom535.coding.net/todo-consumer
        cd todo-consumer
        cp -r . $GOPATH/src/yom535.coding.net/todo-consumer
        cd $GOPATH/src/yom535.coding.net/todo-consumer
        ls -al
        go build .
- name: 发送镜像
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: yom535/example:v1
      pushRemote: true
      registry: registry.us-west-1.aliyuncs.com
timeout: 60
notification: {}
