apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: todo-comsumer
spec:
  host: todo-comsumer
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: todo-comsumer
spec:
  host: todo-comsumer
  subsets:
  - name: v1
    labels:
      version: v1